export enum EAuthAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE = 'LOGOUT_FAILURE',
  REFRESH_TOKENS_SUCCESS = 'REFRESH_TOKENS_SUCCESS',
  REFRESH_TOKENS_FAILURE = 'REFRESH_TOKENS_FAILURE',
}
